apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.projectLabel }}-{{ .Values.frontLabel }}-deployment
  labels:
    app: {{ .Values.projectLabel }}-{{ .Values.frontLabel }}-deployment
    deployment: {{ .Values.projectLabel }}-{{ .Values.frontLabel }}-deployment
    release_job_id: "{{ .Values.ci_job_id | default "default" }}"
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.projectLabel }}-{{ .Values.frontLabel }}-deployment
        image: registry.svo.aero/dpm/airport_digital_ecosystem/gui/fids:{{ .Values.branch | default "development" }}
        command: [ "/bin/sh" ]
        args: [ "-c", "mkdir -p /usr/share/nginx/html/{{ .Values.pathLabel }} && rm -fr /usr/share/nginx/html/{{ .Values.pathLabel }}/* && cp -r /var/build/* /usr/share/nginx/html/{{ .Values.pathLabel }}" ]
        imagePullPolicy: "Always"
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: {{ .Values.frontLabel }}-{{ .Release.Namespace }}-pv-volume
      restartPolicy: Never
      volumes:
        - name: {{ .Values.frontLabel }}-{{ .Release.Namespace }}-pv-volume
          persistentVolumeClaim:
            claimName: {{ .Values.frontLabel }}-pv-claim
      imagePullSecrets:
        - name: regcred
  backoffLimit: 4
  activeDeadlineSeconds: 50
  ttlSecondsAfterFinished: 50
